apiVersion: v1
kind: Service
metadata:
    name: my-lb-service
spec:
    type: LoadBalancer
    selector:
        app.kubernetes.io/name: {{ include "agario-cluster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080